version: '3.8'

services:

  wordpress:
    container_name: ${APP_NAME}-wordpress
    build: ./wordpress
    image: wordpress:php8.1-apache # https://hub.docker.com/_/wordpress
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    volumes:
      - wordpress:/var/www/html
      - ${PERSONAL_PLUGINS_PATH}:/var/www/html/wp-content/plugins
    depends_on:
      - mariadb

  mariadb:
    container_name: ${APP_NAME}-mariadb
    image: mariadb:10.6 #https://hub.docker.com/_/mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
    ports:
      - 3306:3306

  phpMyAdmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin:5.2.0 # https://hub.docker.com/_/phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - phpMyAdmin:/var/www/html
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mariadb

volumes:
  wordpress:
  mariadb:
  phpMyAdmin:
